//! Media probing and ffmpeg argument building for on-demand HLS playback.
//!
//! Every file is exposed as a VOD playlist whose segments are generated by a short-lived
//! ffmpeg process when the player requests them. With stream copy, segment boundaries must
//! fall on video keyframes, so they are derived from the MKV Cues index (fast) or from an
//! ffprobe packet scan (slow, cached on disk).

use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::time::UNIX_EPOCH;
use tokio::process::Command;
use tokio::sync::OnceCell;

use crate::mkv_cues;

/// Target HLS segment length. Stream-copied segments stretch to the next keyframe.
const TARGET_SEGMENT_SECS: f64 = 6.0;
/// A trailing segment shorter than this is merged into the previous one.
const MIN_TAIL_SECS: f64 = 1.0;
/// Stream copy seeks this far before the segment start and trims by timestamp afterwards,
/// because demuxers (notably MPEG-TS) may land past the keyframe we need.
const COPY_PREROLL_SECS: f64 = 2.0;
/// Tolerance for comparing packet timestamps against segment boundaries.
const TS_EPSILON: f64 = 0.0005;

const SIDECAR_PREFIX: &str = "vidbase-";
const COPYABLE_VIDEO_CODECS: &[&str] = &["h264", "hevc"];
const TEXT_SUBTITLE_CODECS: &[&str] = &["subrip", "srt", "ass", "ssa", "webvtt", "mov_text", "text"];
const EXTERNAL_SUBTITLE_EXTENSIONS: &[&str] = &["srt", "vtt", "ass", "ssa"];

pub struct Tools {
    pub ffmpeg: PathBuf,
    pub ffprobe: PathBuf,
}

impl Tools {
    pub fn resolve() -> Self {
        Self {
            ffmpeg: resolve_binary("ffmpeg"),
            ffprobe: resolve_binary("ffprobe"),
        }
    }
}

/// Prefers the sidecar bundled next to the app executable, then well-known install
/// locations (apps launched from Finder/Dock on macOS don't inherit the shell PATH),
/// then whatever is on PATH.
fn resolve_binary(name: &str) -> PathBuf {
    let exe_name = format!("{SIDECAR_PREFIX}{name}{}", std::env::consts::EXE_SUFFIX);
    if let Some(dir) = std::env::current_exe().ok().and_then(|p| p.parent().map(Path::to_path_buf)) {
        let sidecar = dir.join(&exe_name);
        if sidecar.is_file() {
            return sidecar;
        }
    }

    #[cfg(target_os = "macos")]
    for dir in ["/opt/homebrew/bin", "/usr/local/bin", "/opt/local/bin", "/usr/bin"] {
        let p = Path::new(dir).join(name);
        if p.is_file() {
            return p;
        }
    }

    PathBuf::from(name)
}

/// A tokio Command that never flashes a console window on Windows and dies with its handle.
pub fn command(program: &Path) -> Command {
    let mut cmd = Command::new(program);
    cmd.stdin(Stdio::null()).kill_on_drop(true);
    #[cfg(windows)]
    {
        const CREATE_NO_WINDOW: u32 = 0x0800_0000;
        cmd.creation_flags(CREATE_NO_WINDOW);
    }
    cmd
}

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct VideoStream {
    pub index: usize,
    pub codec: String,
    pub profile: Option<String>,
    pub pix_fmt: Option<String>,
    pub width: u32,
    pub height: u32,
}

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct AudioStream {
    pub index: usize,
    pub codec: String,
    pub channels: u32,
    pub language: Option<String>,
    pub title: Option<String>,
    pub default: bool,
}

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct SubtitleTrack {
    /// `s<stream index>` for embedded tracks, `x<n>` for sidecar files next to the video.
    pub id: String,
    pub codec: String,
    pub language: Option<String>,
    pub title: Option<String>,
    pub default: bool,
    pub forced: bool,
    pub external: bool,
}

#[derive(Serialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct MediaInfo {
    pub id: String,
    pub duration: f64,
    pub video: Option<VideoStream>,
    pub audio: Vec<AudioStream>,
    pub subtitles: Vec<SubtitleTrack>,
    /// Whether the video codec can be stream-copied into MPEG-TS for hls.js. The player
    /// must still check that the webview can decode it.
    pub can_copy_video: bool,
}

pub struct Media {
    pub path: PathBuf,
    pub fingerprint: Fingerprint,
    pub start_time: f64,
    pub info: MediaInfo,
    /// Absolute keyframe timestamps (seconds) of the selected video stream. Resolved on the
    /// first stream-copy playlist request, since a packet scan can be slow.
    keyframes: OnceCell<Option<Vec<f64>>>,
    pub external_subtitles: Vec<PathBuf>,
}

#[derive(Clone, Copy, PartialEq, Eq, Hash, Debug)]
pub struct Fingerprint {
    len: u64,
    modified: u128,
}

impl Fingerprint {
    pub fn of(path: &Path) -> Option<Self> {
        let meta = std::fs::metadata(path).ok()?;
        let modified = meta.modified().ok()?.duration_since(UNIX_EPOCH).ok()?.as_nanos();
        Some(Self { len: meta.len(), modified })
    }
}

pub fn media_id(path: &Path) -> String {
    let mut h = DefaultHasher::new();
    path.hash(&mut h);
    format!("{:016x}", h.finish())
}

pub async fn probe(tools: &Tools, path: &Path) -> Result<Media, String> {
    let fingerprint = Fingerprint::of(path).ok_or_else(|| format!("File not found: {}", path.display()))?;

    let output = command(&tools.ffprobe)
        .args(["-v", "error", "-print_format", "json", "-show_format", "-show_streams"])
        .arg(path)
        .output()
        .await
        .map_err(|e| format!("Failed to run ffprobe: {e}"))?;
    if !output.status.success() {
        return Err(format!("ffprobe failed: {}", String::from_utf8_lossy(&output.stderr).trim()));
    }
    let json: Value = serde_json::from_slice(&output.stdout).map_err(|e| format!("Invalid ffprobe output: {e}"))?;

    let format = &json["format"];
    let start_time = parse_f64(&format["start_time"]).unwrap_or(0.0);
    let duration = parse_f64(&format["duration"]).unwrap_or(0.0);
    let streams = json["streams"].as_array().cloned().unwrap_or_default();

    let video = streams
        .iter()
        .filter(|s| s["codec_type"] == "video" && s["disposition"]["attached_pic"] != 1)
        .find_map(|s| {
            Some(VideoStream {
                index: s["index"].as_u64()? as usize,
                codec: s["codec_name"].as_str()?.to_string(),
                profile: s["profile"].as_str().map(str::to_string),
                pix_fmt: s["pix_fmt"].as_str().map(str::to_string),
                width: s["width"].as_u64().unwrap_or(0) as u32,
                height: s["height"].as_u64().unwrap_or(0) as u32,
            })
        });

    let audio = streams
        .iter()
        .filter(|s| s["codec_type"] == "audio")
        .filter_map(|s| {
            Some(AudioStream {
                index: s["index"].as_u64()? as usize,
                codec: s["codec_name"].as_str().unwrap_or("unknown").to_string(),
                channels: s["channels"].as_u64().unwrap_or(2) as u32,
                language: tag(s, "language"),
                title: tag(s, "title"),
                default: s["disposition"]["default"] == 1,
            })
        })
        .collect();

    let mut subtitles: Vec<SubtitleTrack> = streams
        .iter()
        .filter(|s| s["codec_type"] == "subtitle")
        .filter_map(|s| {
            let codec = s["codec_name"].as_str()?;
            // Image-based subtitles (PGS, VobSub) can't be converted to WebVTT.
            if !TEXT_SUBTITLE_CODECS.contains(&codec) {
                return None;
            }
            Some(SubtitleTrack {
                id: format!("s{}", s["index"].as_u64()?),
                codec: codec.to_string(),
                language: tag(s, "language"),
                title: tag(s, "title"),
                default: s["disposition"]["default"] == 1,
                forced: s["disposition"]["forced"] == 1,
                external: false,
            })
        })
        .collect();

    let external_subtitles = find_external_subtitles(path);
    for (n, sub) in external_subtitles.iter().enumerate() {
        subtitles.push(SubtitleTrack {
            id: format!("x{n}"),
            codec: sub.extension().and_then(|e| e.to_str()).unwrap_or("").to_lowercase(),
            language: None,
            title: sub.file_name().map(|n| n.to_string_lossy().to_string()),
            default: false,
            forced: false,
            external: true,
        });
    }

    let info = MediaInfo {
        id: media_id(path),
        duration,
        can_copy_video: video.as_ref().is_some_and(|v| COPYABLE_VIDEO_CODECS.contains(&v.codec.as_str())),
        video,
        audio,
        subtitles,
    };

    Ok(Media {
        path: path.to_path_buf(),
        fingerprint,
        start_time,
        info,
        keyframes: OnceCell::new(),
        external_subtitles,
    })
}

fn parse_f64(v: &Value) -> Option<f64> {
    v.as_str().and_then(|s| s.parse().ok()).or_else(|| v.as_f64())
}

fn tag(stream: &Value, key: &str) -> Option<String> {
    stream["tags"][key]
        .as_str()
        .or_else(|| stream["tags"][key.to_uppercase()].as_str())
        .filter(|s| !s.is_empty() && *s != "und")
        .map(str::to_string)
}

/// Subtitle files sharing the video's base name, e.g. `Movie.srt` or `Movie.pt-BR.srt`.
pub fn find_external_subtitles(video: &Path) -> Vec<PathBuf> {
    let (Some(dir), Some(stem)) = (video.parent(), video.file_stem().and_then(|s| s.to_str())) else {
        return Vec::new();
    };
    let stem = stem.to_lowercase();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut subs: Vec<PathBuf> = entries
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| {
            let ext_ok = p
                .extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| EXTERNAL_SUBTITLE_EXTENSIONS.contains(&e.to_lowercase().as_str()));
            let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("").to_lowercase();
            ext_ok && p.is_file() && (name.starts_with(&format!("{stem}.")))
        })
        .collect();
    subs.sort();
    subs
}

fn keyframe_cache_path(path: &Path, fingerprint: Fingerprint, stream: usize) -> PathBuf {
    let mut h = DefaultHasher::new();
    (path, fingerprint, stream).hash(&mut h);
    cache_dir().join(format!("keyframes-{:016x}.json", h.finish()))
}

pub fn cache_dir() -> PathBuf {
    std::env::temp_dir().join("vidbase_streams")
}

async fn load_keyframes(tools: &Tools, path: &Path, fingerprint: Fingerprint, stream: usize) -> Option<Vec<f64>> {
    let is_matroska = path
        .extension()
        .and_then(|e| e.to_str())
        .is_some_and(|e| matches!(e.to_lowercase().as_str(), "mkv" | "webm"));
    if is_matroska {
        let p = path.to_path_buf();
        if let Ok(Some(kfs)) = tokio::task::spawn_blocking(move || mkv_cues::read_keyframes(&p)).await {
            return Some(kfs);
        }
    }

    let cache = keyframe_cache_path(path, fingerprint, stream);
    if let Some(kfs) = std::fs::read(&cache).ok().and_then(|b| serde_json::from_slice::<Vec<f64>>(&b).ok()) {
        return Some(kfs);
    }

    let kfs = scan_keyframes(tools, path, stream).await?;
    if let Ok(json) = serde_json::to_vec(&kfs) {
        let _ = std::fs::create_dir_all(cache_dir());
        let _ = std::fs::write(&cache, json);
    }
    Some(kfs)
}

/// Reads every video packet header. Correct for any container, but touches the whole file.
async fn scan_keyframes(tools: &Tools, path: &Path, stream: usize) -> Option<Vec<f64>> {
    let output = command(&tools.ffprobe)
        .args(["-v", "error", "-select_streams"])
        .arg(stream.to_string())
        .args(["-show_entries", "packet=pts_time,flags", "-of", "csv=p=0"])
        .arg(path)
        .output()
        .await
        .ok()?;
    let mut kfs: Vec<f64> = String::from_utf8_lossy(&output.stdout)
        .lines()
        .filter_map(|line| {
            let (pts, flags) = line.split_once(',')?;
            flags.contains('K').then(|| pts.parse::<f64>().ok()).flatten()
        })
        .collect();
    kfs.sort_by(|a, b| a.total_cmp(b));
    kfs.dedup();
    (kfs.len() >= 2).then_some(kfs)
}

#[derive(Deserialize, Clone, Copy, PartialEq, Eq, Debug, Default)]
#[serde(rename_all = "lowercase")]
pub enum VideoMode {
    #[default]
    Copy,
    Transcode,
}

#[derive(Clone, Copy, PartialEq, Debug)]
pub struct Segment {
    /// Absolute (container) timestamps in seconds.
    pub start: f64,
    pub end: f64,
}

impl Media {
    /// Resolves the mode actually used and its segment list. Copy mode silently degrades to
    /// transcoding when the codec can't be copied or no keyframe index is available.
    pub async fn plan(&self, tools: &Tools, requested: VideoMode) -> (VideoMode, Vec<Segment>) {
        let keyframes = match (&self.info.video, requested) {
            (Some(video), VideoMode::Copy) if self.info.can_copy_video => self
                .keyframes
                .get_or_init(|| load_keyframes(tools, &self.path, self.fingerprint, video.index))
                .await
                .as_deref(),
            _ => None,
        };
        let mode = if keyframes.is_some() { VideoMode::Copy } else { VideoMode::Transcode };
        let end = self.start_time + self.info.duration;
        (mode, build_segments(self.start_time, end, keyframes))
    }
}

fn build_segments(start: f64, end: f64, keyframes: Option<&[f64]>) -> Vec<Segment> {
    let boundaries = match keyframes {
        Some(kfs) => keyframe_boundaries(kfs, start, end),
        None => fixed_boundaries(start, end),
    };
    boundaries
        .windows(2)
        .map(|w| Segment { start: w[0], end: w[1] })
        .collect()
}

fn keyframe_boundaries(keyframes: &[f64], start: f64, end: f64) -> Vec<f64> {
    let mut bounds = vec![start];
    for &kf in keyframes {
        if kf >= end {
            break;
        }
        if kf - bounds[bounds.len() - 1] >= TARGET_SEGMENT_SECS {
            bounds.push(kf);
        }
    }
    close_boundaries(bounds, end)
}

fn fixed_boundaries(start: f64, end: f64) -> Vec<f64> {
    let count = ((end - start) / TARGET_SEGMENT_SECS).ceil().max(1.0) as usize;
    let bounds = (0..count).map(|i| start + i as f64 * TARGET_SEGMENT_SECS).collect();
    close_boundaries(bounds, end)
}

fn close_boundaries(mut bounds: Vec<f64>, end: f64) -> Vec<f64> {
    if bounds.len() > 1 && end - bounds[bounds.len() - 1] < MIN_TAIL_SECS {
        bounds.pop();
    }
    bounds.push(end);
    bounds
}

pub fn playlist(segments: &[Segment], query: &str) -> String {
    let target = segments
        .iter()
        .map(|s| s.end - s.start)
        .fold(TARGET_SEGMENT_SECS, f64::max)
        .ceil();
    let mut out = format!(
        "#EXTM3U\n#EXT-X-VERSION:3\n#EXT-X-TARGETDURATION:{target}\n#EXT-X-MEDIA-SEQUENCE:0\n#EXT-X-PLAYLIST-TYPE:VOD\n"
    );
    for (i, seg) in segments.iter().enumerate() {
        out.push_str(&format!("#EXTINF:{:.6},\nseg/{i}.ts?{query}\n", seg.end - seg.start));
    }
    out.push_str("#EXT-X-ENDLIST\n");
    out
}

fn secs(v: f64) -> String {
    format!("{:.6}", v.max(0.0))
}

/// `noise` bitstream filter expression that keeps only packets with pts in [start, end).
fn trim_filter(seg: Segment) -> String {
    format!(
        "noise=drop='lt(pts*tb\\,{:.6})+gte(pts*tb\\,{:.6})'",
        seg.start - TS_EPSILON,
        seg.end - TS_EPSILON
    )
}

fn audio_can_copy(audio: &AudioStream) -> bool {
    audio.codec == "aac" && audio.channels <= 6
}

fn aac_args(audio: &AudioStream) -> Vec<String> {
    let channels = audio.channels.clamp(1, 6);
    let mut args = vec!["-c:a".into(), "aac".into(), "-b:a".into(), format!("{}k", 64 * channels.max(2))];
    if audio.channels > 2 {
        // Surround sources (AC-3/DTS are usually "5.1(side)", 7.1 has no AAC config) must be
        // remapped to the standard 5.1 layout; otherwise the encoder signals the layout via a
        // PCE with channel_config 0, which browsers refuse to decode.
        args.extend(["-af".into(), "aformat=channel_layouts=5.1".into()]);
    }
    args
}

/// Builds the ffmpeg arguments producing one MPEG-TS segment on stdout. Timestamps are kept
/// absolute (`-copyts`) so independently generated segments line up in the player.
pub fn segment_args(media: &Media, seg: Segment, audio: Option<&AudioStream>, mode: VideoMode) -> Vec<String> {
    let path = media.path.to_string_lossy().to_string();
    let video = media.info.video.as_ref().map(|v| v.index);
    // -ss/-to are relative to the container start; the trim filter uses absolute pts.
    let rel_start = seg.start - media.start_time;
    let rel_end = seg.end - media.start_time;

    let mut args: Vec<String> = ["-hide_banner", "-loglevel", "error", "-nostdin"].map(String::from).to_vec();

    let mut maps: Vec<String> = Vec::new();
    let mut codecs: Vec<String> = Vec::new();

    match mode {
        VideoMode::Copy => {
            // Seek early, then drop everything outside the segment by timestamp.
            args.extend(["-ss".into(), secs(rel_start - COPY_PREROLL_SECS), "-to".into(), secs(rel_end + 0.5)]);
            args.extend(["-i".into(), path.clone()]);
            if let Some(v) = video {
                maps.extend(["-map".into(), format!("0:{v}")]);
                codecs.extend(["-c:v".into(), "copy".into(), "-bsf:v".into(), trim_filter(seg)]);
            }
            match audio {
                Some(a) if audio_can_copy(a) => {
                    maps.extend(["-map".into(), format!("0:{}", a.index)]);
                    codecs.extend(["-c:a".into(), "copy".into(), "-bsf:a".into(), trim_filter(seg)]);
                }
                Some(a) => {
                    // Re-encoded audio needs a sample-accurate seek, so it gets its own input.
                    args.extend(["-ss".into(), secs(rel_start), "-to".into(), secs(rel_end)]);
                    args.extend(["-i".into(), path.clone()]);
                    maps.extend(["-map".into(), format!("1:{}", a.index)]);
                    codecs.extend(aac_args(a));
                }
                None => {}
            }
        }
        VideoMode::Transcode => {
            args.extend(["-ss".into(), secs(rel_start), "-to".into(), secs(rel_end)]);
            args.extend(["-i".into(), path.clone()]);
            if let Some(v) = video {
                maps.extend(["-map".into(), format!("0:{v}")]);
                codecs.extend(
                    [
                        "-c:v", "libx264", "-preset", "veryfast", "-crf", "21", "-pix_fmt", "yuv420p",
                        "-vf", "scale='min(1920,iw)':-2",
                    ]
                    .map(String::from),
                );
            }
            if let Some(a) = audio {
                maps.extend(["-map".into(), format!("0:{}", a.index)]);
                codecs.extend(aac_args(a));
            }
        }
    }

    args.extend(maps);
    args.extend(codecs);
    args.extend(
        [
            "-copyts", "-avoid_negative_ts", "disabled", "-muxdelay", "0", "-muxpreload", "0", "-f", "mpegts", "pipe:1",
        ]
        .map(String::from),
    );
    args
}

pub fn subtitle_args(source: &Path, stream: Option<usize>) -> Vec<String> {
    let mut args: Vec<String> = ["-hide_banner", "-loglevel", "error", "-nostdin", "-i"].map(String::from).to_vec();
    args.push(source.to_string_lossy().to_string());
    args.extend(["-map".into(), stream.map_or("0:s:0".into(), |s| format!("0:{s}"))]);
    args.extend(["-f", "webvtt", "pipe:1"].map(String::from));
    args
}

pub fn thumbnail_args(path: &Path, time: f64, width: Option<u32>) -> Vec<String> {
    let mut args: Vec<String> = ["-hide_banner", "-loglevel", "error", "-nostdin", "-ss"].map(String::from).to_vec();
    args.push(secs(time));
    args.extend(["-i".into(), path.to_string_lossy().to_string(), "-frames:v".into(), "1".into()]);
    if let Some(w) = width {
        args.extend(["-vf".into(), format!("scale='min({w},iw)':-2")]);
    }
    args.extend(["-q:v", "5", "-f", "image2", "-update", "1", "pipe:1"].map(String::from));
    args
}

#[cfg(test)]
mod tests {
    use super::*;

    fn media(start_time: f64, duration: f64, keyframes: Option<Vec<f64>>) -> Media {
        Media {
            path: PathBuf::from("/videos/a.mkv"),
            fingerprint: Fingerprint { len: 0, modified: 0 },
            start_time,
            info: MediaInfo {
                id: "x".into(),
                duration,
                video: Some(VideoStream {
                    index: 0,
                    codec: "h264".into(),
                    profile: None,
                    pix_fmt: None,
                    width: 1280,
                    height: 720,
                }),
                audio: vec![],
                subtitles: vec![],
                can_copy_video: true,
            },
            keyframes: OnceCell::new_with(Some(keyframes)),
            external_subtitles: vec![],
        }
    }

    fn audio(codec: &str, channels: u32) -> AudioStream {
        AudioStream { index: 2, codec: codec.into(), channels, language: None, title: None, default: true }
    }

    #[test]
    fn copy_segments_start_on_keyframes_and_cover_the_file() {
        let kfs: Vec<f64> = (0..37).map(|i| i as f64 * 5.005).collect();
        let segs = build_segments(0.0, 180.021, Some(&kfs));
        assert_eq!(segs[0], Segment { start: 0.0, end: 10.01 });
        assert!((segs[1].start - 10.01).abs() < 1e-9);
        assert_eq!(segs.last().unwrap().end, 180.021);
        for w in segs.windows(2) {
            assert_eq!(w[0].end, w[1].start);
        }
    }

    #[test]
    fn copy_segments_respect_container_start_time() {
        let segs = build_segments(1.472978, 21.472978, Some(&[1.483, 6.488, 11.493, 16.498]));
        assert_eq!(segs.first().unwrap().start, 1.472978);
        assert_eq!(segs[1].start, 11.493);
        assert_eq!(segs.last().unwrap().end, 21.472978);
    }

    #[test]
    fn short_tail_is_merged() {
        let segs = build_segments(0.0, 12.5, None);
        assert_eq!(segs, vec![Segment { start: 0.0, end: 6.0 }, Segment { start: 6.0, end: 12.5 }]);
    }

    #[tokio::test]
    async fn copy_without_keyframes_falls_back_to_transcode() {
        let tools = Tools { ffmpeg: "ffmpeg".into(), ffprobe: "ffprobe".into() };
        let (mode, segs) = media(0.0, 60.0, None).plan(&tools, VideoMode::Copy).await;
        assert_eq!(mode, VideoMode::Transcode);
        assert_eq!(segs.len(), 10);
    }

    #[test]
    fn playlist_lists_every_segment() {
        let segs = [Segment { start: 0.0, end: 10.01 }, Segment { start: 10.01, end: 13.0 }];
        let pl = playlist(&segs, "audio=1&video=copy");
        assert!(pl.contains("#EXT-X-TARGETDURATION:11\n"));
        assert!(pl.contains("#EXTINF:10.010000,\nseg/0.ts?audio=1&video=copy\n"));
        assert!(pl.contains("seg/1.ts?audio=1&video=copy\n#EXT-X-ENDLIST"));
    }

    #[test]
    fn copy_args_use_relative_seek_and_absolute_trim() {
        let m = media(1.5, 60.0, Some(vec![1.5, 11.5]));
        let seg = Segment { start: 11.5, end: 21.5 };
        let args = segment_args(&m, seg, Some(&audio("ac3", 6)), VideoMode::Copy).join(" ");
        assert!(args.contains("-ss 8.000000 -to 20.500000 -i /videos/a.mkv"), "{args}");
        assert!(args.contains("-ss 10.000000 -to 20.000000 -i /videos/a.mkv"), "{args}");
        assert!(args.contains("-map 0:0 -map 1:2"), "{args}");
        assert!(args.contains("noise=drop='lt(pts*tb\\,11.499500)+gte(pts*tb\\,21.499500)'"), "{args}");
        assert!(args.contains("-c:a aac -b:a 384k -af aformat=channel_layouts=5.1"), "{args}");
    }

    #[test]
    fn copy_args_copy_compatible_aac_from_single_input() {
        let m = media(0.0, 60.0, Some(vec![0.0, 10.0]));
        let args = segment_args(&m, Segment { start: 0.0, end: 10.0 }, Some(&audio("aac", 2)), VideoMode::Copy);
        assert_eq!(args.iter().filter(|a| *a == "-i").count(), 1);
        assert!(args.join(" ").contains("-c:a copy -bsf:a noise"));
    }
}
